name: whatsapp_clone_flutter
description: A high-fidelity WhatsApp clone built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animates_transitions: ^0.0.3
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  google_fonts: ^6.2.1
  rename_app: ^1.6.5

dev_dependencies:
   flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png